# Generated by Django 5.2 on 2025-04-23 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_data',
            fields=[
                ('emp_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('passport_img', models.ImageField(blank=True, null=True, upload_to='employee_passports/')),
                ('badge_num', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('address', models.TextField(default='', max_length=255)),
                ('department', models.CharField(choices=[('medical', 'Medical'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('administration', 'Administration'), ('maintenance', 'Maintenance'), ('it', 'IT'), ('finance', 'Finance'), ('hr', 'Human Resources')], max_length=70)),
                ('job_title', models.CharField(max_length=30)),
                ('date_of_hire', models.DateField()),
                ('employment_types', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Intern')], max_length=50)),
                ('supervisor_manager', models.BooleanField(default=False, help_text='Check if employee is a supervisor or manager')),
                ('monthly_salary', models.CharField(max_length=13)),
                ('highest_qualification', models.CharField(max_length=60)),
                ('specialization', models.CharField(max_length=60)),
                ('years_of_experience', models.IntegerField()),
                ('licenses', models.TextField(max_length=255)),
            ],
        ),
    ]
