# Generated by Django 5.2 on 2025-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employee_data_passport_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='passport_img',
            field=models.ImageField(blank=True, null=True, upload_to='employee_passports/'),
        ),
    ]
