# Generated by Django 5.2 on 2025-04-25 09:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_data_passport_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='date_of_birth',
            field=models.DateField(help_text='Format: YYYY-MM-DD', validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 4, 25))]),
        ),
    ]
