# Generated by Django 5.2 on 2025-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_data_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='Select Gender', max_length=10),
        ),
    ]
