# Generated by Django 5.2 on 2025-04-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='department',
            field=models.CharField(choices=[('Select Department', 'Select Department'), ('medical', 'Medical'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('administration', 'Administration'), ('maintenance', 'Maintenance'), ('it', 'IT'), ('finance', 'Finance'), ('hr', 'Human Resources')], max_length=70),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='employment_types',
            field=models.CharField(choices=[('Select Employment_type', 'Select Employment_type'), ('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Intern')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='gender',
            field=models.CharField(choices=[('Select Gender', 'Select Gender'), ('male', 'male'), ('female', 'female')], max_length=20),
        ),
    ]
