# Generated by Django 5.2 on 2025-04-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_employee_data_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='department',
            field=models.CharField(choices=[('medical', 'Medical'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('administration', 'Administration'), ('maintenance', 'Maintenance'), ('it', 'IT'), ('finance', 'Finance'), ('hr', 'Human Resources')], default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='employment_types',
            field=models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Intern')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=10),
        ),
    ]
