# Generated by Django 5.2 on 2025-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_data_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='supervisor_manager',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Is this employee a supervisor or manager?', max_length=3),
        ),
    ]
