# Generated by Django 5.2 on 2025-05-09 10:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_data_supervisor_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='date_of_birth',
            field=models.DateField(help_text='Format: YYYY-MM-DD', validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 5, 9))]),
        ),
    ]
